# -*- coding: utf-8 -*-
"""movierecommendor(new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W1UUvB0K4k7
    h0HkKsARbRUzR8f6zqh-x
"""

import pandas as pd
import numpy as np 
import pickle
movie = pd.read_csv("C:\\Users\\misht\\Downloads\\TMDB_movie_dataset_v11.csv",encoding='latin1', on_bad_lines='skip')
movie=movie[movie['vote_count']>50].copy()

movie = movie[['id', 'title', 'overview', 'genres', 'keywords', 'tagline']]

movie.dropna(inplace=True)

from re import M
movie['genres']=movie['genres'].apply(lambda x:x.split(','))
movie['keywords']=movie['keywords'].apply(lambda x:x.split(','))
movie['tagline']=movie['tagline'].apply(lambda x:x.split(' '))
movie['overview']=movie['overview'].apply(lambda x:x.split(' '))
movie['tags']=(movie['genres']*5)+(movie['keywords']*2)+(movie['tagline']*2)+movie['overview']
movie['tags']=movie['tags'].apply(lambda x: " ".join(x).lower())

import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def text_stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return y
movie['tags']=movie['tags'].apply(text_stem)
movie['tags']=movie['tags'].apply(lambda x:" ".join(x))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tf=TfidfVectorizer(max_features=10000,stop_words='english')
spm=tf.fit_transform(movie['tags'])
user_weights=np.zeros((1,10000))
def update_weights(movie_title,action):
  global user_weights
  try:
    rewards = {'like': 0.05, 'dislike': -0.1, 'watchlist': 0.1}
    reward = rewards.get(action, 0)
    idx=movie[movie['title']==movie_title].index[0]
    mv=spm[idx].toarray()
    user_weights+=reward*mv
    pickle.dump(user_weights, open('user_weights.pkl', 'wb'))
  except Exception as e:
    print("Movie title not found in dataset.")
def recommendor(text,alpha=0.05):
  ind=movie[movie['title']==text].index[0]
  l=[]
  c=0
  user_score = np.asarray(spm.dot(user_weights.T)).flatten()#dimension movie x 1
  distances=cosine_similarity(spm[ind],spm)[0]+alpha*user_score#enumerate -> gives a dictionary of {ind:value}
  distance=list(enumerate(distances)) #we have to convert it to list as enumerate operator creates an iterator and distance[0] because cosine_similarity gives a 2d array even if you compare only one movie with every other movie
  distance=sorted(distance,reverse=True,key=lambda x:x[1])#we use x[1] so that it sort on bases of score not index
  distance=distance[1:6]
  for i in distance:
    l.append(movie.iloc[i[0]].title)

  return l



import pickle

# 1. Save the filtered movie DataFrame
# We save it as a dictionary because it's easier for the frontend to load
pickle.dump(movie.to_dict(), open('movie_list.pkl', 'wb'))

# 2. Save the Sparse Matrix (This is your spm.pkl)
# This contains the TF-IDF weights for all movies
pickle.dump(spm, open('spm.pkl', 'wb'))

# 3. Save the Vectorizer (Optional, but good for future searches)
pickle.dump(tf, open('tfidf_vectorizer.pkl', 'wb'))

